# Exercise 1: Reusable Workflows

## Problem

#You have a workflow that you want to reuse in other repositories. You want to avoid copying and pasting the workflow file in each repository.

#The current workflow definition:

#```yaml
name: "Caller Workflow"

on:
  workflow_dispatch:
   
jobs:
  call-workflow:
    uses: aalliioozz/newsandbox/.github/workflows/called_workflow.yml@main
    with:
      actor: Ali
