name: "Lesson 2 - Exercise 4"

on:
  workflow_dispatch: 
  # push:
  #   branches:
  #     - main
  #     # Match the release branches: releases/1, releases/2, etc.
  #     - "releases/[0-9]"

# Add your solution below this line
# Concurrency configuration at workflow level
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/heads/releases/') }}

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Build and release
        run: |
          echo "Building branch: ${{ github.ref }} for OS: ${{ matrix.os }}"
          sleep 10
